[env:feather_rp2040_can]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather_can
framework = arduino
extra_scripts = pre:scripts/platformio_sync_profile.py
board_build.core = earlephilhower
lib_deps = autowp/autowp-mcp2515
build_flags = -DDRIVER_MCP2515

[env:waveshare_ESP32_S3_RS485_CAN]
platform = espressif32
board = esp32s3box
framework = arduino
extra_scripts = pre:scripts/platformio_sync_profile.py
build_flags =
    -DDRIVER_TWAI
    -DESP32_DASHBOARD
    -DDASH_DEFAULT_HW=2
    -DTWAI_TX_PIN=GPIO_NUM_15
    -DTWAI_RX_PIN=GPIO_NUM_16
    -DPIN_LED=14
    -std=gnu++17
build_unflags = -std=gnu++11
monitor_speed = 115200

