
#log-queries=extra
log-queries
log-facility=/root/dnsmasq.log

#filter-AAAA

address=/tesla.cn/127.0.0.1
address=/tesla.com/127.0.0.1
address=/teslamotors.com/127.0.0.1
address=/tesla.services/127.0.0.1
address=/tesla.cn/::
address=/tesla.com/::
address=/teslamotors.com/::
address=/tesla.services/::

server=/connman.vn.cloud.tesla.cn/223.5.5.5
server=/www.tesla.cn/223.5.5.5
server=/media-server-me.tesla.cn/223.5.5.5
server=/nav-prd-maps.tesla.cn/223.5.5.5

server=/community-api.tesla.cn/223.5.5.5
server=/china-community-app.tesla.cn/223.5.5.5
server=/video.tesla.cn/223.5.5.5
server=/digitalassets.tesla.com/223.5.5.5
server=/hermes-prd.vn.cloud.tesla.cn/223.5.5.5




#server=/cx.tesla.cn/223.5.5.5
#server=/auth.tesla.cn/223.5.5.5


# middle
#server=/api-ap-prd.vn.cloud.tesla.cn/223.5.5.5
#server=/api-prd.vn.cloud.tesla.cn/223.5.5.5
#server=/hermes-stream-prd.vn.cloud.tesla.cn/223.5.5.5

# remote control
#server=/vehicle-files.prd.cnn1.vn.cloud.tesla.cn/223.5.5.5
#server=/hermes-x2-api.prd.vn.cloud.tesla.cn/223.5.5.5
server=/signaling.vn.cloud.tesla.cn/223.5.5.5
~
~